name: Test Mod Build (Pull Request)

on: pull_request

jobs:
  test_assemble_mod:
    name: Test Assemble Mod for ${{ matrix.friendlyName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: forge112
            friendlyName: Forge 1.12
          # Add other modules and their friendly names as needed
          # - module: forge189
          #   friendlyName: Forge 1.8.9
          # - module: forge1710
          #   friendlyName: Forge 1.7.10
          # ... and so on
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "8"

      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v3
        if: ${{ always() }}
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v3
        if: ${{ always() }}
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Assemble mod with Gradle for ${{ matrix.friendlyName }}
        run: ./gradlew ${{ matrix.module }}:assemble -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000